### ISSUE TITLE
Babel compile error: accounting/utils.js: unknown node of type undefined with constructor "Function"

### ISSUE THREAD

**Issue by paulcwatts** [cibernox/ember-cli-accounting#25]
My project's vitals:

* Ember 2.11
* Ember Data 2.11
* Ember CLI 2.11
* Node: 6.9.2

If I run "ember install ember-cli-accounting" and then "ember serve", I get this error:

```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: accounting/utils.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
ReferenceError: accounting/utils.js: unknown node of type undefined with constructor "Function"
    at CodeGenerator.print (.../node_modules/babel-core/lib/generation/index.js:274:13)
    at NodePrinter.plain (.../node_modules/babel-core/lib/generation/node/printer.js:37:27)
    at CodeGenerator.MemberExpression (.../node_modules/babel-core/lib/generation/generators/expressions.js:324:9)
    at CodeGenerator.print (.../node_modules/babel-core/lib/generation/index.js:289:20)
    at NodePrinter.plain (.../node_modules/babel-core/lib/generation/node/printer.js:37:27)
    at CodeGenerator.CallExpression (.../node_modules/babel-core/lib/generation/generators/expressions.js:182:9)
    at CodeGenerator.print (.../node_modules/babel-core/lib/generation/index.js:289:20)
    at NodePrinter.plain (.../node_modules/babel-core/lib/generation/node/printer.js:37:27)
    at CodeGenerator.AssignmentExpression (.../node_modules/babel-core/lib/generation/generators/expressions.js:277:9)
    at CodeGenerator.print (.../node_modules/babel-core/lib/generation/index.js:289:20)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (.../node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (.../node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (.../node_modules/broccoli-babel-transpiler/index.js:35:10)
    at EmberApp._addonTree (.../node_modules/ember-cli/lib/broccoli/ember-app.js:940:29)
    at EmberApp._processedVendorTree (.../node_modules/ember-cli/lib/broccoli/ember-app.js:974:20)
    at EmberApp._processedExternalTree (.../node_modules/ember-cli/lib/broccoli/ember-app.js:1005:21)
    at EmberApp.appAndDependencies (.../node_modules/ember-cli/lib/broccoli/ember-app.js:1114:30)
    at EmberApp.javascript .../node_modules/ember-cli/lib/broccoli/ember-app.js:1244:34)
    at EmberApp.toArray (.../node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (.../node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
```

However, when I add it to a newly-created project with the same specs, it works fine. I haven't figured out what's different about my project than a newly-created project. Any ideas on how to investigate this?

It's worth noting that using the standard accounting.js and my own vendor shim works fine.

**Comment by cibernox** [comment]
I haven't updated this project in ages. I'll check it. 
You can indeed use accounting.js yourself, but you will loose the convenience helpers this addon provides.

**Comment by cibernox** [comment]
Can you check again? I have updated several dependencies and release 2.0 (dropped support for ember 1.X). Perhaps it's fixed now.

**Comment by paulcwatts** [comment]
Unfortunately I'm getting the same error, even with 2.0. I even deleted node_modules, tmp, dist and bower_components.

Sadly I'm out of my depth trying to debug Babel code generation errors.

**Comment by cibernox** [comment]
that is weird because I'm using this addon without any problem, and I am on the same version of ember and ember-data, and works perfectly for me.

Can you create a reproduction?

**Comment by paulcwatts** [comment]
I was trying to do that, both from a new project but also trying to remove things in my current project until I could get it to work -- neither were successful. 

My project isn't that large, but I am using a few off-the-beaten path things that seem like they could affect it:

1. generators (ember-concurrency)
2. async/await using the Babel polyfill.
3. The new Ember module shims

I'll continue trying to find what is causing it. I wonder if it's something I'm importing that is adding a global variable?

**Comment by paulcwatts** [comment]
I found a reproduction for this:

```
ember new accounting-test
cd accounting-test
ember install ember-cli-accounting
ember build
ember install ember-awesome-macros
ember build
```

I'm not certain why ember-awesome-macros is causing this, although that addon does include https://github.com/kellyselden/babel-plugin-fake-import-specifiers which does some munging of imports.

**Comment by paulcwatts** [comment]
As of the latest version of ember-awesome-macros (v0.3.3) and commit https://github.com/kellyselden/ember-awesome-macros/commit/43fb467d1430c346ad5f901d53378781e989681a which replaced that babel plugin, this is fixed!
